number:
  questions: 4
sql:
  word_learned: "id IN (SELECT word_id FROM answers WHERE correct = 1 
  	AND id IN (SELECT answer_id FROM results WHERE lesson_id IN
  	(SELECT id FROM lessons WHERE user_id = ?)))"
  not_learned: "id NOT IN (SELECT word_id FROM answers WHERE correct = 1 
  	AND id IN (SELECT answer_id FROM results WHERE lesson_id IN 
  	(SELECT id FROM lessons WHERE user_id = ?)))"